export const TICKERS: { symbol: string; name: string; price: string; change: string; percent: string; up: boolean }[] = [];

export const FEATURES = [
  {
    title: "Three-Statement Model",
    arabic: "نموذج القوائم الثلاث",
    description: "Dynamic integration of income statement, balance sheet, and cash flow with Saudi-specific GAAP/IFRS treatments.",
    icon: "◎",
    tag: "INSTITUTIONAL",
    viz: "3S",
  },
  {
    title: "DCF Engine",
    arabic: "محرك التدفقات النقدية",
    description: "High-precision discounted cash flow models with automated WACC calculation and sensitivity analysis.",
    icon: "⬡",
    tag: "PRECISION",
    viz: "DCF",
  },
  {
    title: "LBO Analytics",
    arabic: "تحليلات الاستحواذ",
    description: "Complex leveraged buyout modeling with multi-tier debt structures and exit IRR visualizations.",
    icon: "✦",
    tag: "STRATEGY",
    viz: "LBO",
  },
  {
    title: "AI Research",
    arabic: "أبحاث الذكاء الاصطني",
    description: "Automated equity research memos generated by Gemini 2.0 Flash, trained on Saudi Tadawul disclosures.",
    icon: "△",
    tag: "INTELLIGENCE",
    viz: "AI",
  },
  {
    title: "Shariah Screening",
    arabic: "الفحص الشرعي",
    description: "Institutional-grade Shariah compliance engine with real-time ratio tracking and purification data.",
    icon: "✧",
    tag: "COMPLIANCE",
    viz: "Shariah",
  },
  {
    title: "Scenario Manager",
    arabic: "مدير السيناريوهات",
    description: "Multi-scenario stress testing (Bull/Base/Bear) for all models with real-time comparison views.",
    icon: "⊞",
    tag: "STRATEGY",
    viz: "Scenario",
  },
];
